CREATE TABLE IF NOT EXISTS scans (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    host TEXT,
    server_type TEXT,
    ssl_version TEXT,
    cipher TEXT,
    header_values TEXT,
    key_type TEXT,
    key_size TEXT,
    serial_number TEXT,
    subject TEXT,
    issuer TEXT,
    valid_until TEXT,
    expires_in TEXT,
    has_expired BOOLEAN,
    scan_month INTEGER,
    status BOOLEAN,
    rsa_modulus_n TEXT,
    rsa_modulus_e TEXT,
    protocols TEXT,
    ai_analysis TEXT,
    weak_ciphers BOOLEAN,
    sslv3_supported BOOLEAN,
    tls1_supported BOOLEAN,
    tls1_1_supported BOOLEAN,
    heartbleed BOOLEAN,
    scan_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);